version: '3'
services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
      - '/home/website-new/klausuren/:/app/public/'
    ports:
      - "80:3000"
