name: Deploy 

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: create env file
      run: echo ${{secrets.ENV}} >> .env.production
    - name: Run the Compose
      run: docker-compose up --build --detach
